### PR TITLE
Section 6: 6.2c Custom Tabular Input Group

### PR DESCRIPTION
**Pull request by julia-rom**
# Description

- created a custom tabular input group for 6.2c as it has more fields and different inputs (selects vs text).  Added a vertical display. Maybe we can get Al's input on whether they should just all be vertical rows for consistency.
- Not sure if I like the design of where the delete icon is, open to other suggestions
- Fixed a bug in section 5 tabular input group where add-unit-input wasn't showing
- todo: create separate task to add modal pop up for deleting items in tabular input to avoid accidental deletions
- I updated the question order. **6.2d** is now **6.2c**, since in the previous question I combined 6.2b/c from the original order, and just called it 6.2b. 

Testing
- create a new site to ensure data is clean
- go to section 6
- scroll down to 6.2c
- test adding new measurement rows
- if purpose is 'Other', additional input should appear to specify category
- test editing/updating data and refreshing the page to ensure data is correct

Fixes # ([80](https://github.com/globalmangrovewatch/gmw-users/issues/80))

### CODE REVIEW

**Comment by mmnoo** [comment]
Found a bug:

Steps to reproduce:
- make new site
- go to section 6
- add measurement row for 6.2c 
``` 
{
                "type": "dandelions",
                "count": "6",
                "source": "Nursery",
                "purpose": {
                    "purpose": "Other",
                    "other": ""
                },
                "id": "c4480f87-c546-4bac-9e45-0c412fa80404"
            }
```
- click save
- refresh page

Expected results:
The form shows with the added values and a save success message

Actual results:
app breaks. Console complains about not being able to read properties of null for a map.

**Review by mmnoo — CHANGES_REQUESTED** [review]
Bug needs fix. See comment.

**Comment by julia-rom** [comment]
hey @mmnoo , I'm having trouble reproducing this bug - I have seen it before though before I made some code changes. I'm wondering if we're using the same review app link incase one is an old one? I just tried with [this one ](https://gmw-users-staging-7c26443.herokuapp.com/). Let me know if you get the same issue. If I am still unable to reproduce maybe lets hop on a screenshare?

**Comment by mmnoo** [comment]
> hey @mmnoo , I'm having trouble reproducing this bug - I have seen it before I made some code changes. I'm wondering if we're using the same review app link incase it's an old one? I just tried with [this one ](https://gmw-users-staging-7c26443.herokuapp.com/). Let me know if you get the same issue. If I am still unable to reproduce maybe lets hop on a screenshare?

Did the same test steps as in bug description. No prob. Then went to edit same measurement a couple of times and it broke. 

something about useMemo?
Screen Shot 2022-07-27 at 10 10 06 AM

**Comment by julia-rom** [comment]
@mmnoo thanks for catching this bug. I fixed this by providing empty array defaults to `mangroveAssociatedSpecies` and `mangroveSpeciesUsed`. The error was occurring because it was trying to map onto something that was undefined. Also caught another bug where 'other' wasn't updating in the tabular input.

Let me know if you see any more errors!

**Comment by mmnoo** [comment]
Still a bug. 

Steps to reproduce:

- make new site
- go to section 6
- add measurement row for 6.2c
  {
        "question_id": "6.2c",
        "answer_value": [
            {
                "type": "53rtwer",
                "count": "7",
                "source": "Nursery",
                "purpose": {
                    "purpose": "Other",
                    "other": "twtetwetw"
                },
                "id": "a0d54796-7f82-4d11-bc8c-903f07617971"
            }
        ]
    },
- click save
- refresh page,
- Looks good, edit purpose to be 'Coastal defence'

Expected results:
The form shows with the added values and a save success message

Actual results:
app breaks. Console complains about not being able to read properties of null for a map.

**Comment by julia-rom** [comment]
@mmnoo thanks for catching this - I realized I missed setting a default empty array for one of the form properties. Fingers crossed it works now! Let me know

**Comment by mmnoo** [comment]
That issue is fixed. I found another, which I will let you prioritize. When you make a measurement and save it with an other value, refresh, then edit purpose to have Coastal Defence as a value, save, refresh. Select a purpose of other again, and it is filled with the pervious value which should have been erased from the server data. (I verified with with postman)

**Pull request merged**
