### PR TITLE
Feature: tabular delete check for input rows

### PR DESCRIPTION
**Pull request by julia-rom**
- Add 'are you sure you want to delete this row' to tabular input groups in Costs, Pre-restoration Assessment, and Site Interventions
- Using ConfirmPrompt (yay thanks for making this @mmnoo )

### CODE REVIEW

**Review by mmnoo — CHANGES_REQUESTED** [review]
Code looks good. 

But bugs:
- 5.3g doesnt show a prompt for deletes
- Site intervention throws error on load `s.map is not a function`. This happened for the site called 'Stuff'

**Comment by julia-rom** [comment]
> Code looks good.
> 
> But bugs:
> 
> * 5.3g doesnt show a prompt for deletes
> * Site intervention throws error on load `s.map is not a function`. This happened for the site called 'Stuff'

ohh thanks for testing and catching this! will investigate

**Comment by julia-rom** [comment]
> > Code looks good.
> > But bugs:
> > 
> > * 5.3g doesnt show a prompt for deletes
> > * Site intervention throws error on load `s.map is not a function`. This happened for the site called 'Stuff'
> 
> ohh thanks for testing and catching this! will investigate 🕵️‍♀️

pushed an update for 5.3g, as for the map error, can you test to see if this is happening on new sites? I did some data restructuring in section 6 for the answers schema so sites that were created before this update will error

**Review by mmnoo — APPROVED** [review]
works

**Pull request merged**
